version: '2'
services:
  aws_ir:
    build: .
    volumes:
      - ~/.aws:/root/.aws
      - .:/aws_ir/
    environment:
      - EDDA_SERVER=172.16.31.127
      - EDDA_PORT=8080
      - EDDA_BASE_URL=/api/v2/
